// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9iBX0R-zg3OrMFPvCqPtj0bk9tkBNziU',
    appId: '1:462865760925:web:899a901d40246fdde50a74',
    messagingSenderId: '462865760925',
    projectId: 'video-uploading-func',
    authDomain: 'video-uploading-func.firebaseapp.com',
    databaseURL: 'https://video-uploading-func-default-rtdb.firebaseio.com',
    storageBucket: 'video-uploading-func.appspot.com',
    measurementId: 'G-1NLWT15XL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVT_8P1kC710arn4hCP2KJZuHUsQ9dps',
    appId: '1:462865760925:android:01937616b6866860e50a74',
    messagingSenderId: '462865760925',
    projectId: 'video-uploading-func',
    databaseURL: 'https://video-uploading-func-default-rtdb.firebaseio.com',
    storageBucket: 'video-uploading-func.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbOeomFuAdSoUjw2L06TlAhc8XtRXUVCI',
    appId: '1:462865760925:ios:3a340e0e94843f9be50a74',
    messagingSenderId: '462865760925',
    projectId: 'video-uploading-func',
    databaseURL: 'https://video-uploading-func-default-rtdb.firebaseio.com',
    storageBucket: 'video-uploading-func.appspot.com',
    iosBundleId: 'com.example.videoUploading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbOeomFuAdSoUjw2L06TlAhc8XtRXUVCI',
    appId: '1:462865760925:ios:dc702508c6ab500ce50a74',
    messagingSenderId: '462865760925',
    projectId: 'video-uploading-func',
    databaseURL: 'https://video-uploading-func-default-rtdb.firebaseio.com',
    storageBucket: 'video-uploading-func.appspot.com',
    iosBundleId: 'com.example.videoUploading.RunnerTests',
  );
}
